_config.yml
_posts/2015-01-27-welcome-2015-technology-innovation-fellows.md
feed.xml

Also fixes a few warnings that arose when running `jekyll serve`.

Add post welcoming the 2015 T&I Fellows

---

css/site.css
jobs/automation-engineer/index.md
jobs/bewd/index.md
jobs/devops/index.md
jobs/index.md

This pull request does the following:
- Adds a generic "jobs" page where we can list all of our job openings
- Adds listings for each of the current BEWD positions
- Adds some button styles
@Scotchester

Add back-end developer job listings

---

jobs/automation-engineer/index.md
jobs/bewd/index.md
jobs/devops/index.md

Adds the exact job title to match what is on USAJobs.

Be more explicit about the official job title

---

_posts/2015-09-15-we're-looking-for-an-experienced-manager-to-lead-our-UX-team.md

because we just don't need it
@marteki @Scotchester

remove "is" before the colon

---

_posts/2015-09-15-we're-looking-for-an-experienced-manager-to-lead-our-UX-team.md

add link to the now-live USA Jobs listing for this position.
- @benguhin 
- @ascott1

add link to USA Jobs page

---

jobs/summer-intern/index.md

I know it's an absurdly short job listing, but I got the summer internship listing up.
- @cfarm 
- @ascott1

Summer Internship listing

---

README.md

There's currently nothing at all, this fixes that. It's not comprehensive, but it's a place to start.

Added content for a sensible readme

---

_posts/2015-12-10-readme-refresh-day.md

Correct link

---

_posts/2015-12-10-readme-refresh-day.md

I am "iterating" on this "article", per "agile"
:cry:

Correct link text

---

index.html

update privacy act statement

---

_config.yml
_includes/header.html
_layouts/default.html
index.html

fix asset paths and permalinks for articles

---

_layouts/post.html

fix sidebar links on posts

---

_config.yml
_posts/2014-06-23-now-recruiting-2015-fellows.md

Update to Rouge for syntax highligting

---

_posts/2016-04-22-next-cio.md
css/site.css

The youtube embed on the CIO blog post was causing a horizontal scroll on mobile devices. This should fix it.
@marteki @higs4281

responsive youtube embed

---

_config.yml

This changes the description of the site to be more broadly about technology.

d&d => technology

---

_posts/2016-04-22-next-cio.md

Uses the word in place of the number.

8 => eight

---

_layouts/post.html
_posts/2015-10-19-federal-icons-in-the-open.md

Remove Disqus commenting system

---

jobs/graphic-design/index.md

Thanks for catching this, @moka
@Scotchester Could you review?

Change job link to http from https

---

jobs/graphic-design/index.md

Make it easier to email about the job.

add mailto link for graphic designer job

---

_includes/header.html
_layouts/default.html
_posts/2016-04-22-next-cio.md

After #82, forks stopped being able to resolve the static assets. This PR uses [the latest Jekyll guidance for working with GitHub pages](https://jekyllrb.com/docs/github-pages/#project-page-url-structure) to ensure that assets work everywhere! Fixes #84.
1. https://scotchester.github.io/cfpb.github.io/
- @cfarm 
- @ascott1
- @marteki

Fix the loading of static assets on forks

---

index.html

- @ielerol 
- @marteki 
- @cfarm 
- @higs4281

Comment out the list of current openings

---

_posts/2016-10-06-next-cio.md

This adds a link to the application page on consumerfinance.gov.

Add link to live CIO posting

---

_posts/2016-10-06-next-cio.md

Remove link to CIO posting

---

_config.yml
_includes/header.html
_layouts/post.html
css/site.css
index.html

- Updated the email signup forms across https://cfpb.github.io/

Update email signup forms

---

css/site.css
index.html

Addresses @chosak's comments in https://github.com/cfpb/cfpb.github.io/pull/250

Fixup typos to new copy

---

index.html

Noted in https://github.com/cfpb/cfpb.github.io/pull/252#pullrequestreview-1048198065

Don't underline the icon in 'View all repositories'
